# select the base image to build upon
FROM ubuntu:latest

# Leave a bread crumb in case people need help
MAINTAINER Ron Kurr "kurron@jvmguy.com"

# Tell Docker how to run the date command when it starts 
ENTRYPOINT echo "The current time is $(date)"

